/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'bmearns' at '7/17/15 8:22 PM' with Gradle 2.5
 *
 * @author bmearns, @date 7/17/15 8:22 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
